In [ ]:
#Notebook to evalute the quality of the linear relaxation of the SDP relaxation for 
#maxcut.

<h1>functions and evaluation of SDP and LP relaxation of maxcut <h1>

<h1>Table of contents <h1>   
    0. Load maxCutRelaxations notebook,functions , set seed<br>
    1. Code for table 2: TSPLIB<br>
    2. Code for table 3: Network repository graph<br>
    3. Code for table 1: Erods-Renyi random instances of Mirka & Williamson <br>
    4. Code for table 4: Quotient of chi(G) to z_gw<br>
    5. Table for table 5: Quotient of z_sp to z_gw<br>
    6. Code for figure 1.
    

<h2>0. Load maxCutRelaxations notebook, set seedfunctions .<h2>

In [1]:
using NBInclude,TSPLIB,StatsBase,Arpack,LightGraphs,LinearAlgebra,Statistics,Random,Distributions,Plots
 

In [2]:
@nbinclude("MaxCutRelaxations.ipynb")


tableEigenFooling (generic function with 1 method)

In [3]:
Random.seed!(12341234)

TaskLocalRNG()

<h3>Functions  <h3>

In [ ]:
#function that computes a cut by solving the linear programs Z_sp and then Z_sd, by using the 
#rounding procedure of Goemans and Williamson. Once
#the matrix Z_sd is found, we produce 100 random cuts and present the best. 
#@param matrix adjMatrix: a matrix for which to compute a cut. 
function giveFoundCutValue(adjMatrix)
    sizeOfProblem = size(adjMatrix,1)
    solveEigenRel = eigenRelaxation(adjMatrix, giveEigenRelParameters(adjMatrix,false))[1]
    A = SDeigenEnhanced(adjMatrix,solveEigenRel)[1]
     #make sure we got a positive-definite result
    # A = 0.5 * (cutFinder + cutFinder')
    A += (max(0, -eigmin(A)) + 1e-14) * Matrix(I, size(A, 1), size(A, 1))
    result = Matrix(cholesky(A))
    max_cut = -1
     for i in 1:100
    gweval = result' * randn(sizeOfProblem)
    partition = (findall(gweval .>= 0), findall(gweval .< 0))
    cut = sum(adjMatrix[partition...])
       if cut > max_cut
      max_cut = cut
      end
   end
    return(max_cut)
end

In [ ]:
#function that returns the value of the quotients 0.5m+0.25Z_sp / 0.5m+0.25GW, 0.5m+0.25Z_sp/0.5m+0.25Z_sd and the value
#of the cut given by the function giveFoundCutValue.
#@param matrix adjMatrix: the matrix for which to compute these values.
function giveQuotientAndCut(adjMatrix)
    
      eigenSol = eigenRelaxation(adjMatrix, giveEigenRelParameters(adjMatrix,false))
         goeSol = GoemansPrimal(adjMatrix)[2]
         sdeigenSol = SDeigen(adjMatrix)
    
    return((eigenSol[2]/goeSol,eigenSol[2]/sdeigenSol[2] , giveFoundCutValue(adjMatrix)))
    end

In [ ]:
#function to load the graphs of the Network Repository, given in a .txt file 
# whose rows are of the form a b, indicating an edge between vertices a and b.
# The first two lines are irrelavant.
#one of the graphs has weights  (in a third column) and must be dealt separately. 
#@param string fileAdress the path of the file to read.
#@param int graphSize the dimensions of the graph to load.
#@param bool isWeighted: indicates if the edges of the graph have weights.
function loadGraph(fileAdress,graphSize,isWeighted)
    adjMatrix = zeros(graphSize,graphSize)
    if(isWeighted == false)
         open(fileAdress) do file   
             for ln in eachline(file)
             values = split(ln," ")
             value1 = parse(Int64,values[1])
             value2 =  parse(Int64,values[2])     
             adjMatrix[value1,value2] = 1
            adjMatrix[value2,value1] = 1
            end
        end
    
    else
        open(fileAdress) do file   
              for ln in eachline(file)
             values = split(ln," ")
             value1 = parse(Int64,values[1])
             value2 =  parse(Int64,values[2])
             value3 =   parse(Float64,values[3])
             adjMatrix[value1,value2] = value3
            adjMatrix[value2,value1] = value3
            end
        end
    end
    
     # check symmetry
    issymmetric(adjMatrix)|| throw(ArgumentError("Adjacency matrix must be symmetric."))
    return(adjMatrix)
end
  
    
    

<h2> 1. Code for table 2: TSPLIB<h2>

In [ ]:
#These graphs can be found in the following link: 
#https://juliahub.com/ui/Packages/TSPLIB/qDJ8z/0.1.2

<h2>bayg29<h2>

In [ ]:
tsp = readTSPLIB(:bayg29)
bayg29 = tsp.weights
giveQuotientAndCut(bayg29)

<h2>bays29<h2>

In [ ]:
tsp = readTSPLIB(:bays29)
bays29 = tsp.weights
giveQuotientAndCut(bays29)

<h2>berlin52<h2>

In [ ]:
tsp = readTSPLIB(:berlin52)
berlin52 = tsp.weights
giveQuotientAndCut(berlin52)

<h2>bier127<h2>

In [ ]:
tsp = readTSPLIB(:bier127)
bier127 = tsp.weights
giveQuotientAndCut(bier127)

<h2>brazil58<h2>

In [ ]:
tsp = readTSPLIB(:brazil58)
brazil58 = tsp.weights
giveQuotientAndCut(brazil58)

<h2>brg180<h2>

In [ ]:
tsp = readTSPLIB(:brg180)
brg180 = tsp.weights
giveQuotientAndCut(brg180)

<h2>ch130<h2>

In [ ]:
tsp = readTSPLIB(:ch130)
ch130 = tsp.weights
giveQuotientAndCut(ch130)

<h2>ch150<h2>

In [ ]:
tsp = readTSPLIB(:ch150)
ch150 = tsp.weights
giveQuotientAndCut(ch150)

<h2>d198<h2>

In [ ]:
tsp = readTSPLIB(:d198)
d198 = tsp.weights
giveQuotientAndCut(d198)

<h2>eil101<h2>

In [ ]:
tsp = readTSPLIB(:eil101)
eil101 = tsp.weights
giveQuotientAndCut(eil101)

<h2>gr120<h2>

In [ ]:
tsp = readTSPLIB(:gr120)
gr120 = tsp.weights
giveQuotientAndCut(gr120)

<h2>gr137<h2>

In [ ]:
tsp = readTSPLIB(:gr137)
gr137 = tsp.weights
giveQuotientAndCut(gr137)

<h2>gr202<h2>

In [ ]:
tsp = readTSPLIB(:gr202)
gr202 = tsp.weights
giveQuotientAndCut(gr202)

<h2>gr96<h2>

In [ ]:
tsp = readTSPLIB(:gr96)
gr96 = tsp.weights
giveQuotientAndCut(gr96)

<h2>kroA100<h2>

In [ ]:
tsp = readTSPLIB(:kroA100)
kroA100 = tsp.weights
giveQuotientAndCut(kroA100)

<h2>a280<h2>

In [ ]:
tsp = readTSPLIB(:a280)
a280 = tsp.weights
giveQuotientAndCut(a280)

<h2> 2. Code for table 3: Network repository graph<h2>

In [ ]:
#These graphs can be found in the following link: 
#https://networkrepository.com/networks.php

<h2>ENZYMES8<h2>

In [ ]:
enzymes8 = loadGraph("graphNetwork\\ENZYMES8.edges",88,false)
giveQuotientAndCut(enzymes8)

<h2>eco-stmarks<h2>

In [ ]:
eco_stmarks = loadGraph("graphNetwork\\eco-stmarks.edges",54,true)
giveQuotientAndCut(eco_stmarks)

<h2>johnson16-2-4<h2>

In [ ]:
johnson1624 = loadGraph("graphNetwork\\johnson16-2-4.mtx",120,false)
giveQuotientAndCut(johnson1624)

<h2>hamming6-2<h2>

In [ ]:
hamming62 = loadGraph("graphNetwork\\hamming6-2.mtx",64,false)
giveQuotientAndCut(hamming62)

<h2>ia-infect-hyper<h2>

In [ ]:
ia_infect_hyper = loadGraph("graphNetwork\\ia-infect-hyper.mtx",113,false)
giveQuotientAndCut(ia_infect_hyper)

<h2>soc-dolphins<h2>

In [ ]:
soc_dolphins = loadGraph("graphNetwork\\soc-dolphins.mtx",62,false)
giveQuotientAndCut(soc_dolphins)

<h2>email-enron-only<h2>

In [ ]:
email_enron_only= loadGraph("graphNetwork\\email-enron-only.mtx",143,false)
giveQuotientAndCut(email_enron_only)

<h2>dwt_209<h2>

In [ ]:
dwt_209 = loadGraph("graphNetwork\\dwt_209.mtx",209,false)
giveQuotientAndCut(dwt_209)

<h2>inf-USAir97<h2>

In [ ]:
inf_USAir97 = loadGraph("graphNetwork\\inf-USAir97.mtx",332,true)
giveQuotientAndCut(inf_USAir97)


<h2>ca-netscience<h2>

In [ ]:
ca_netscience = loadGraph("graphNetwork\\ca-netscience.mtx",379,false)
giveQuotientAndCut(ca_netscience)

<h2>ia-infect-dublin<h2>

In [ ]:
ia_infect_dublin= loadGraph("graphNetwork\\ia-infect-dublin.mtx",410,false)
giveQuotientAndCut(ia_infect_dublin)

<h2>road-chesapeake<h2>

In [ ]:
road_chesapeake = loadGraph("graphNetwork\\road-chesapeake.mtx",39,false)
giveQuotientAndCut(road_chesapeake)

<h2>Erdos991<h2>

In [ ]:
Erdos991 = loadGraph("graphNetwork\\Erdos991.mtx",492,false)
giveQuotientAndCut(Erdos991)

<h2>dwt_503<h2>

In [ ]:
dwt_503 = loadGraph("graphNetwork\\dwt_503.mtx",503,false)
giveQuotientAndCut(dwt_503)

<h2>p-hat700-1<h2>

In [ ]:
p_hat700_1 = loadGraph("graphNetwork\\p-hat700-1.mtx",700,false)
giveQuotientAndCut(p_hat700_1)

<h2>DD687<h2>

In [ ]:
#care! This graph has self loops.
DD687 = loadGraph("graphNetwork\\DD687.edges",725,false)
giveQuotientAndCut(DD687)

<h2>email-univ<h2>

In [ ]:
email_univ= loadGraph("graphNetwork\\email-univ.edges",1133,false)
giveQuotientAndCut(email_univ)

<h2> Code for table 1: Erods-Renyi random instances of Mirka & Williamson <h2>

<h3>G(50,0.1)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=50 p=0.1.txt",50,false)
#G = Matrix(adjacency_matrix(erdos_renyi(50,0.1)))
giveQuotientAndCut(G)

<h3>G(50,0.25)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=50 p=0.25.txt",50,false)
giveQuotientAndCut(G)

<h3>G(50,0.5)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=50 p=0.5.txt",50,false)
giveQuotientAndCut(G)

<h3>G(50,0.75)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=50 p=0.75.txt",50,false)
giveQuotientAndCut(G)

<h3>G(100,0.1)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=100 p=0.1.txt",100,false)
giveQuotientAndCut(G)

<h3>G(100,0.25)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=100 p=0.25.txt",100,false)
giveQuotientAndCut(G)

<h3>G(100,0.5)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=100 p=0.5.txt",100,false)
giveQuotientAndCut(G)

<h3>G(100,0.75)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=100 p=0.75.txt",100,false)
giveQuotientAndCut(G)

<h3>G(200,0.1)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=200 p=0.1.txt",200,false)
giveQuotientAndCut(G)

<h3>G(200,0.25)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=200 p=0.25.txt",200,false)
giveQuotientAndCut(G)

<h3>G(200,0.5)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=200 p=0.5.txt",200,false)
giveQuotientAndCut(G)

<h3>G(200,0.75)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=200 p=0.75.txt",200,false)
giveQuotientAndCut(G)

<h3>G(350,0.1)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=350 p=0.1.txt",350,false)
giveQuotientAndCut(G)

<h3>G(350,0.25)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=350 p=0.25.txt",350,false)
giveQuotientAndCut(G)

<h3>G(350,0.5)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=350 p=0.5.txt",350,false)
giveQuotientAndCut(G)

<h3>G(350,0.75)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=350 p=0.75.txt",350,false)
giveQuotientAndCut(G)

<h3>G(500,0.1)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=500 p=0.1.txt",500,false)
giveQuotientAndCut(G)

<h3>G(500,0.25)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=500 p=0.25.txt",500,false)
giveQuotientAndCut(G)

<h3>G(500,0.5)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=500 p=0.5.txt",500,false)
giveQuotientAndCut(G)

<h3>G(500,0.75)<h3>

In [ ]:
G = loadGraph("ErdosRenyi\\random n=500 p=0.75.txt",500,false)
giveQuotientAndCut(G)

<h2>4.  Code for table 4 and table 5: Quotient of chi(G) to z_gw, and  Quotient of z_sp to z_gw  .<h2>

<h3> a. k=4, l= 5<h3>

In [4]:
answer64_4_5=tableEigenFooling(64,4,5)


6-element Vector{Float64}:
 1.0208649757086665
 1.241288204577846
 0.0026412145287263975
 0.00872635824416017
 0.0
 0.0

In [5]:
answer100_4_5=tableEigenFooling(100,4,5)


6-element Vector{Float64}:
 1.017201631101175
 1.4167753385299755
 0.002447364635125527
 0.007361697868184715
 0.0
 0.0

In [6]:
answer196_4_5=tableEigenFooling(196,4,5)


6-element Vector{Float64}:
 1.0121273991139828
 1.7599658972149004
 0.0017536500408746377
 0.003201565868712626
 0.0
 0.0

In [7]:
answer_400_4_5=tableEigenFooling(400,4,5)


6-element Vector{Float64}:
 1.009782594704004
 2.2886377520738175
 0.0011028714726230783
 0.0033509114992715384
 0.0
 0.0

<h3>b. k=10, l=10<h3>

In [8]:
answer_64_6_10=tableEigenFooling(64,6,10)

6-element Vector{Float64}:
 1.0288485337269624
 1.137001103957155
 0.002409332632211075
 0.007760930439462225
 0.0
 0.0

In [9]:
answer_100_6_10=tableEigenFooling(100,6,10)


6-element Vector{Float64}:
 1.0243293415007044
 1.2777154446189471
 0.0012055795051903642
 0.007455480134922394
 0.0
 0.0

In [10]:
answer_196_6_10=tableEigenFooling(196,6,10)


6-element Vector{Float64}:
 1.019507238654882
 1.546199587976714
 0.0010141390704828568
 0.004720599132675943
 0.0
 0.0

In [11]:
answer_400_10_10=tableEigenFooling(400,6,10)


6-element Vector{Float64}:
 1.0132984486513934
 1.961809135755642
 0.0006538399595328774
 0.0023500750627662437
 0.0
 0.0

<h2> 6. Code for figure 1 <h2>

<h3>a. Functions <h3>

In [ ]:
function IterVsSDP(typeGraph,interval,p,graphDeg,rounds)
    len = length( interval)
    SolArrayMax = zeros(len)
    SolArrayMedian = zeros(len)
    SolArrayMin = zeros(len)


    count = 1
     for i in interval
         print(i)
        flush(stdout)        
       
         values = zeros(rounds)
         valuesTotalCut  = zeros(rounds)
         graphs = Array{Any,1}(undef,rounds)
       
            if(typeGraph == "erdosLog")
              [graphs[r]=   Matrix(adjacency_matrix(erdos_renyi(i,3*log(i)/i))) for r in 1:rounds]  
            elseif (typeGraph == "erdosNP")
                  [graphs[r]=  Matrix(adjacency_matrix(erdos_renyi(i,1/(2i)))) for r in 1:rounds]  
            elseif (typeGraph == "regular")
                  [graphs[r]=   Matrix(adjacency_matrix(random_regular_graph(i,graphDeg))) for r in 1:rounds]  
            elseif (typeGraph == "linearReg")
             graphDeglinReg = Int64(round(i/10))
                if (isodd(i*graphDeglinReg))
                      graphDeglinReg=graphDeglinReg+1
                end
             [graphs[r]=  Matrix(adjacency_matrix(random_regular_graph(i,graphDeglinReg))) for r in 1:rounds]  
               
              elseif (typeGraph == "sqrtReg")
             graphDegSqrtReg = Int64(round( sqrt(i)))
                if (isodd(i*graphDegSqrtReg))
                      graphDegSqrtReg=graphDegSqrtReg+1
                end
             [graphs[r]=  Matrix(adjacency_matrix(random_regular_graph(i,graphDegSqrtReg))) for r in 1:rounds]  
               
           
        else
             [graphs[r]=    Matrix(adjacency_matrix(erdos_renyi(i, p))) for r in 1:rounds]  

                    end    
   
        for j in 1: rounds  
     
   eigenSol = solverIteratelyLP(graphs[j],i)
   sdpSol =   GoemansPrimal(graphs[j])[3]
         
               values[j] = eigenSol/sdpSol
                     
         end
               SolArrayMedian[count]= median(values)
               SolArrayMax[count] = maximum(values)
               SolArrayMin[count]= minimum(values)    
       
     count = count+1      
        end
   
   
    results = zeros(len,3)
    results[:,1]  = SolArrayMax
    results[:,2]  = SolArrayMedian
    results[:,3]  = SolArrayMin
   
    return(results,interval)    
       
end


In [ ]:

function lpVsSDP(typeGraph,interval,p,graphDeg,rounds)
    len = length( interval)
    SolArrayMax = zeros(len)
    SolArrayMedian = zeros(len)
    SolArrayMin = zeros(len)


    count = 1
     for i in interval
         print(i)
        flush(stdout)        
       
         values = zeros(rounds)
         valuesTotalCut  = zeros(rounds)
         graphs = Array{Any,1}(undef,rounds)
       
            if(typeGraph == "erdosLog")
              [graphs[r]=   Matrix(adjacency_matrix(erdos_renyi(i,3*log(i)/i))) for r in 1:rounds]  
            elseif (typeGraph == "erdosNP")
                  [graphs[r]=  Matrix(adjacency_matrix(erdos_renyi(i,1/(2i)))) for r in 1:rounds]  
            elseif (typeGraph == "regular")
                  [graphs[r]=   Matrix(adjacency_matrix(random_regular_graph(i,graphDeg))) for r in 1:rounds]  
            elseif (typeGraph == "linearReg")
             graphDeglinReg = Int64(round(i/10))
                if (isodd(i*graphDeglinReg))
                      graphDeglinReg=graphDeglinReg+1
                end
             [graphs[r]=  Matrix(adjacency_matrix(random_regular_graph(i,graphDeglinReg))) for r in 1:rounds]  
               
              elseif (typeGraph == "sqrtReg")
             graphDegSqrtReg = Int64(round( sqrt(i)))
                if (isodd(i*graphDegSqrtReg))
                      graphDegSqrtReg=graphDegSqrtReg+1
                end
             [graphs[r]=  Matrix(adjacency_matrix(random_regular_graph(i,graphDegSqrtReg))) for r in 1:rounds]  
               
           
        else
             [graphs[r]=    Matrix(adjacency_matrix(erdos_renyi(i, p))) for r in 1:rounds]  

                    end    
   
        for j in 1: rounds  
     
   eigenSol = eigenRelaxation(graphs[j], giveEigenRelParameters(graphs[j],false))
   sdpSol =   GoemansPrimal(graphs[j])[3]
         
               values[j] = eigenSol[3]/sdpSol
                     
         end
               SolArrayMedian[count]= median(values)
               SolArrayMax[count] = maximum(values)
               SolArrayMin[count]= minimum(values)    
       
     count = count+1      
        end
   
   
    results = zeros(len,3)
    results[:,1]  = SolArrayMax
    results[:,2]  = SolArrayMedian
    results[:,3]  = SolArrayMin
   
    return(results,interval)    
       
end



In [ ]:
#if eigens = 0, the method is not using eigenvectors.
# if eigens = i>0, uses eigens from 1 to i.
function solverIteratelyLP(adjMatrix,numCuts)
   
    n = size(adjMatrix)[1]
     m = Model(Mosek.Optimizer)
    set_silent(m)
     
      @variable(m,-1<=X[1:n,1:n]<=1,Symmetric )
         for i in 1:n
        @constraint(m,X[i,i]==1)
         
    end
  @objective(m,Max,dot(-adjMatrix,X))
    status = optimize!(m)
   
     
     for s in 1:numCuts
      maxEigVecto = eigen(value.(X)).vectors[:,1]
      @constraint(m, transpose(maxEigVecto)*X*maxEigVecto>=0)
    status = optimize!(m)
      end  
         
    return( objective_value(m))

end

<h3> b. Set a new seed <h3>

In [ ]:
# set a new seed for this computation
Random.seed!(1019068721)

<h3> c. Compute and plot results<h3>

In [ ]:

#resfinal = lpVsSDP("erdos",20:10:190,0.3,5,5)
#Erdosp03 = transpose(resfinal[1])

#resIterFinal = IterVsSDP("erdos",20:10:190,0.3,5,3)
#values1 = transpose(resIterFinal[1])


a2 = vec(Erdosp03[1,:]-Erdosp03[2,:])
b2 = vec(Erdosp03[2,:]-Erdosp03[1,:])
σs = (a2,abs.(b2))

a3 = vec(values1[1,:]-values1[2,:])
b3 = vec(values1[2,:]-values1[1,:])
σs3 = (a3,abs.(b3))


y = plot(resfinal[2], Erdosp03[2,:],marker=(:diamond, 3, 1.),xaxis ="Size of graph",label="Eigen cuts",yaxis="Lp_S/SDP" ,size = (800, 500),ylim=(1, 3),linestyle =:dash,ribbon =σs,colour="green",legend=:topleft )
plot!(resIterFinal[2], values1[2,:],marker=(:square, 3, 1.),ylabel="Cuts/GW",xaxis ="size of graph",yaxis="Lp/SDP" ,label="Oracle cuts",size = (800, 500),ylim=(1, 3),linestyle =:dash,ribbon =σs3,colour="orange")